/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_winhandiao_PrimitiveTypeBytecode */

#ifndef _Included_com_github_winhandiao_PrimitiveTypeBytecode
#define _Included_com_github_winhandiao_PrimitiveTypeBytecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    stateIfBigEndian
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_stateIfBigEndian
  (JNIEnv *, jclass);

/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    getIntBitCast
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_getIntBitCast
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    getCharBitCast
 * Signature: (C)S
 */
JNIEXPORT jshort JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_getCharBitCast
  (JNIEnv *, jclass, jchar);

/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    getDoubleBitCast
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_getDoubleBitCast
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    getFloatBitCast
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_getFloatBitCast
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    getDoubleBytecode
 * Signature: (DZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_getDoubleBytecode__DZ
  (JNIEnv *, jclass, jdouble, jboolean);

/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    getDoubleBytecode
 * Signature: (D)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_getDoubleBytecode__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    getFloatByteCode
 * Signature: (FZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_getFloatByteCode__FZ
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_github_winhandiao_PrimitiveTypeBytecode
 * Method:    getFloatByteCode
 * Signature: (F)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_winhandiao_PrimitiveTypeBytecode_getFloatByteCode__F
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
