/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_winhandiao_ClassTypeBytecode */

#ifndef _Included_com_github_winhandiao_ClassTypeBytecode
#define _Included_com_github_winhandiao_ClassTypeBytecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_winhandiao_ClassTypeBytecode
 * Method:    stateIfBigEndian
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_winhandiao_ClassTypeBytecode_stateIfBigEndian
  (JNIEnv *, jclass);

/*
 * Class:     com_github_winhandiao_ClassTypeBytecode
 * Method:    getInstanceBytecode
 * Signature: (Ljava/lang/Object;Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_winhandiao_ClassTypeBytecode_getInstanceBytecode__Ljava_lang_Object_2Z
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_github_winhandiao_ClassTypeBytecode
 * Method:    getInstanceBytecode
 * Signature: (Ljava/lang/Object;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_winhandiao_ClassTypeBytecode_getInstanceBytecode__Ljava_lang_Object_2
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
